-- Bingo Ranked initial schema
-- All timestamps stored as ISO-8601 strings (UTC) for portability and easy debugging.

PRAGMA foreign_keys = ON;
PRAGMA journal_mode = WAL;

CREATE TABLE IF NOT EXISTS users (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  username      TEXT    NOT NULL UNIQUE COLLATE NOCASE,
  email         TEXT    UNIQUE COLLATE NOCASE,
  password_hash TEXT    NOT NULL,
  created_at    TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at    TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- One MC account per site account (1-to-1).
CREATE TABLE IF NOT EXISTS mc_accounts (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id      INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  mc_uuid      TEXT    NOT NULL UNIQUE,
  mc_username  TEXT    NOT NULL,
  linked_at    TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX IF NOT EXISTS idx_mc_accounts_uuid ON mc_accounts(mc_uuid);

-- Short-lived codes generated in-game by /link, redeemed on the website.
CREATE TABLE IF NOT EXISTS link_codes (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  code         TEXT    NOT NULL UNIQUE,
  mc_uuid      TEXT    NOT NULL,
  mc_username  TEXT    NOT NULL,
  created_at   TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  expires_at   TEXT    NOT NULL,
  used_at      TEXT
);
CREATE INDEX IF NOT EXISTS idx_link_codes_uuid ON link_codes(mc_uuid);
CREATE INDEX IF NOT EXISTS idx_link_codes_expires ON link_codes(expires_at);

-- Refresh tokens: stored as sha256 hash so a DB leak doesn't expose live sessions.
CREATE TABLE IF NOT EXISTS refresh_tokens (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash  TEXT    NOT NULL UNIQUE,
  created_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  expires_at  TEXT    NOT NULL,
  revoked_at  TEXT
);
CREATE INDEX IF NOT EXISTS idx_refresh_user ON refresh_tokens(user_id);

-- Each completed bingo game. game_uuid is generated by the mod and prevents
-- replay/duplicate submissions if the network blips.
CREATE TABLE IF NOT EXISTS bingo_games (
  id               INTEGER PRIMARY KEY AUTOINCREMENT,
  game_uuid        TEXT    NOT NULL UNIQUE,
  mode             TEXT    NOT NULL,
  started_at       TEXT    NOT NULL,
  ended_at         TEXT    NOT NULL,
  duration_seconds INTEGER NOT NULL,
  winning_team     TEXT,
  win_condition    TEXT,
  created_at       TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX IF NOT EXISTS idx_games_ended ON bingo_games(ended_at);
CREATE INDEX IF NOT EXISTS idx_games_mode ON bingo_games(mode);

-- Every player who participated in a game, with their team and winner flag.
-- We snapshot the MC username at game time so renames don't rewrite history.
CREATE TABLE IF NOT EXISTS game_participants (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  game_id     INTEGER NOT NULL REFERENCES bingo_games(id) ON DELETE CASCADE,
  mc_uuid     TEXT    NOT NULL,
  mc_username TEXT    NOT NULL,
  team        TEXT    NOT NULL,
  is_winner   INTEGER NOT NULL CHECK (is_winner IN (0, 1)),
  UNIQUE(game_id, mc_uuid)
);
CREATE INDEX IF NOT EXISTS idx_participants_uuid ON game_participants(mc_uuid);
CREATE INDEX IF NOT EXISTS idx_participants_game ON game_participants(game_id);

-- Track which migrations have run.
CREATE TABLE IF NOT EXISTS schema_migrations (
  version    TEXT PRIMARY KEY,
  applied_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
